### ISSUE TITLE
Auto correct dev script local blockchain time

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#129]
**Description**
Some period of time is being added to the proposal. Says proposal period is 5min and also that it ends in 11min 

**Steps to Reproduce**
1. Start Creating Contributor Proposal
2. Create two options 
3. Add Transfer&Mint action to each (use two different account addresses)
4. Finish creating proposal 
5. Confirm transaction on Metamaks
6. Go to  newly created Proposal Preview page

**Expected behavior**
"Ends in" time should correspond to Proposal duration period

**Screenrecord**
https://user-images.githubusercontent.com/37701286/178221643-99c6be7c-624e-4d1a-af27-763927d5ecad.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
On screen record, tried refreshing the page because proposal data didn't load, same thing happend for couple of other proposals that I have created. This behavior is described in issue #107.

**Comment by rossneilson** [comment]
I think I know the issue here and its a devscript issue. Its a little complicated but we can manipulate time on the local blockchain and so the script is not properly correcting it back to current time. You can see in the video the duration is correct its just that the proposal creation time is different from actual time since the local blockhcain is out of sync. 
Lets make this into an issue to automate this.

**Comment by rossneilson** [comment]
Closing in favour of this since the fix is required in contracts repo 
https://github.com/DXgovernance/dxdao-contracts/issues/206
