### ISSUE TITLE
Allow raw transactions to be built

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#304]
We have started from the happiest path with the action builder but we do also need to allow for power users to make their own actions.

We should have a toggle at the very bottom of the contract list that says "Advanced options v"
Once toggled a "Raw transaction" option will be seen below.
Once clicked we should allow the user to manually enter as inputs:
- `to`
- `data`
- `value`

Then we need to add this to the transaction, it will show in the UI as an unknown action. We didn't really plan much around this feature so hopefully it isn't too hard to manually set these values.

**Comment by dcrescimbeni** [comment]
Should we also support entering `data`?

**Comment by rossneilson** [comment]
> Should we also support entering `data`?

Yep, we don't need any validation here either we just directly take what the user inputs

**Comment by dcrescimbeni** [comment]
Should we add an info line?

Right now we show "Unknown action", but maybe we can show something like "Raw transaction => address for X amount" or something like that?

Also keep the red highlight and icon like the current Unknown action.

**Comment by rossneilson** [comment]
> Should we add an info line?
> 
> Right now we show "Unknown action", but maybe we can show something like "Raw transaction => address for X amount" or something like that?
> 
> Also keep the red highlight and icon like the current Unknown action.

Nice idea, we should still say unknown action I think but adding the to address part is good and we can add the X amount of the value is more than 0

**Comment by dcrescimbeni** [comment]
Since raw transactions are basically unknown actions, I think it would be OK if we show the transaction data (`to` and `value`) for all unknown actions.

This is a card preview (compact):

![Image](https://user-images.githubusercontent.com/75996796/191129138-2312185c-7874-4964-b8e9-f6c6f54839c4.png)

And the proposal page:

![Image](https://user-images.githubusercontent.com/75996796/191128671-97d26337-fb2a-4112-856d-b5f0d752bec0.png)


Also the proposal creation page:

![Image](https://user-images.githubusercontent.com/75996796/191128793-d0aa361f-f4e6-4c9f-bcdb-ab0ac0e45eb8.png)

Currently, we need to click on "Raw transaction" button to show the raw data, but I think we should just display it without a toggle. Also the address below "Interact with" is redundant and should be removed.

I think the "Interact with" part is ok, since it shows the value in ETH.

This are substantial changes, so please share your feedback.
