### ISSUE TITLE
Colour code voting buttons

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#331]
**User Story**
As a user I want to be able to more easily vote for the correct option using the option titles. 

**Alternative Solutions**
We have colours assigned to the voting options in their descriptions but not on the voting buttons, we should just duplicate the same colours over there. It would be good also to ensure these colours are random, maybe based off a hashed seed(if they are not already). The true against should however always be red. 

We can add an additional feature here also which adds validation to setting these titles in the action builder so that duplicate names are not allowed. Including setting the name "Against".

**Additional context**
We let users specify these titles in the action builder and someone could, and in the beta, has set a fake "Against" vote, potentially misleading users.

**Comment by MiltonTulli** [comment]
Just to be on the same page, the scope of this task will be: 
1. Adding the same action colors to voting buttons. The "Against" option is always red. We use the option index to select from `theme.colors.votes`. Will continue using that since hashed random color will require a bigger refactor.
2. Ensure no duplicate action name & preventing user to add the "Against" option ("Against" is set by default with no calls and can't be changed currently)

**Comment by rossneilson** [comment]
Correct yes, I wasnt sure of how we currently do things so that makes sense. Will make another issue for hashed colorus
