### ISSUE TITLE
IPFS non-base58 error

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#60]
**Description**
It seems occasionally we get an error creating proposals when uploading metadata to ipfs. On localhost this appears as a full error "non-base58". Not sure how to reliably replicate

**Steps to Reproduce**

1. Create proposal
2. Add text
3. Create proposal
4. Check if errors - shouldn't go to transaction if error is found

**Expected behavior**
Creates transaction and description is viewable in proposal page after

**Comment by rossneilson** [comment]
Test with deployment to ensure not a localhost issue

**Comment by MiltonTulli** [comment]
@rossneilson I found this issue working in another feature. Not sure what is the issue (ipfs related) but added a try/catch around the promise. At least is not braking the app now. Not sure if this issue was created to handle the error gracefully (we needed to do that anyways) or investigate on ipfs issue. 1st is done here => 

https://github.com/DXgovernance/DAVI/pull/137/files#diff-0a1ce10a26fd8d5f22c6f5cbd45b778af3fa1ce05779b5bcb1cdd198cae893abR147-R155

**Comment by rossneilson** [comment]
Nice, and ipfs upload part works or no?

**Comment by MiltonTulli** [comment]
> Nice, and ipfs upload part works or no?

Yes. There were 2 issues: 
- 1. (most important) We were trying to create multiple instances of ipfs executing the`useIPFSNode` hook more than once. According to the docs we should do this once for one repo. 
- 2. Since the ipfs.add was failing and we weren't catching that promise failing, the app was crashing. 

Both issues fixed here https://github.com/DXgovernance/DAVI/pull/137
